name: Publish to GitHub Packages
on: push
jobs:
  delete-snapshot-npm-package-1:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
      - id: get-package-id
        run: |
          VERSIONS=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -L https://api.github.com/users/stephanpelikan/packages/npm/grommet/versions)
          ID=$(echo $VERSIONS | jq --exit-status '.[] | select(.name == "${{ steps.get-version.outputs.version }}") | .id')
          echo "PACKAGE_ID=${ID:-not-found}" >> $GITHUB_ENV
      - uses: actions/delete-package-versions@v4.1.1
        with:
          package-name: 'grommet'
          package-type: 'npm'
          package-version-ids: ${{ env.PACKAGE_ID }}
  publish:
    runs-on: ubuntu-latest
    needs: delete-snapshot-npm-package-1
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
      - run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "//npm.pkg.github.com/stephanpelikan/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "@stephanpelikan:registry=https://npm.pkg.github.com/stephanpelikan" >> ~/.npmrc
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
